- name: Install Prometheus via Helm
  hosts: all
  become: true

  tasks:
    - name: Add Prometheus community repo
      become: true
      become_user: k8s
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Install kube-prometheus-stack
      become: true
      become_user: k8s
      kubernetes.core.helm:
        name: monitoring
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: yes
        # 注意: このチャートは非常に巨大なため、
        # 実行には数分〜10分程度かかることがあります。